# Generated by Django 3.1.1 on 2020-09-15 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200916_0504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmoneytransactionsmodel',
            old_name='total_after_transacion',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='transfermoneytransactionsmodel',
            old_name='balance',
            new_name='balance_amount',
        ),
    ]
