# Generated by Django 3.1.1 on 2020-09-15 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200916_0505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmoneytransactionsmodel',
            old_name='balance',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='transfermoneytransactionsmodel',
            old_name='balance_amount',
            new_name='balance',
        ),
    ]
